// CareOS Hospital Operating System — Agent Contracts
import { AgentContract, AgentId } from '../types/hospital';

export const AGENT_CONTRACTS: Record<AgentId, AgentContract> = {
  orchestrator: {
    id: 'orchestrator',
    name: 'CareOS Orchestrator',
    domain: 'Hospital Operating Core',
    responsibilities: [
      'Understanding user requests & clinical intent',
      'Orchestrating agent collaboration and task planning',
      'Cross-departmental aggregation and correlation',
      'Enforcing verification constraints and final response generation',
    ],
    allowedData: ['Global hospital state', 'Agent message queues', 'Task registries', 'Event bus'],
    tools: ['agent_router', 'task_planner', 'event_broadcaster', 'verification_engine'],
    permissions: ['dispatch_tasks', 'read_all_agent_outputs', 'publish_audit_log'],
    inputSchema: '{ query: string, context?: object, patient_id?: string }',
    outputSchema: '{ execution_plan: object, agent_results: array, final_synthesis: object }',
    escalationRules: 'Escalate to Hospital Medical Superintendent or Ops Director on critical unresolvable deadlocks.',
    failureBehavior: 'Fallback to deterministic rule-based orchestration; report limited confidence.',
  },
  journey_agent: {
    id: 'journey_agent',
    name: 'Patient Journey Agent',
    domain: 'Patient Trajectory & Milestones',
    responsibilities: [
      'Reconstruct end-to-end patient journey timelines',
      'Identify current stage and pending dependencies',
      'Pinpoint milestone breaches and determine immediate next actions',
    ],
    allowedData: ['Patient registration', 'Milestone timestamps', 'Stage dependencies', 'Doctor referrals'],
    tools: ['journey_reconstructor', 'milestone_checker', 'dependency_resolver'],
    permissions: ['read_patient_record', 'update_journey_state', 'flag_milestone_delay'],
    inputSchema: '{ patient_id: string, include_history?: boolean }',
    outputSchema: '{ current_stage: string, pending_dependencies: string[], next_action: string }',
    escalationRules: 'If waiting time in current stage exceeds 45 mins, trigger Journey Stage Delay alert.',
    failureBehavior: 'Return last confirmed checkpoint with STALE_DATA warning.',
  },
  appointment_agent: {
    id: 'appointment_agent',
    name: 'Appointment Agent',
    domain: 'Outpatient & Consultant Scheduling',
    responsibilities: [
      'Doctor availability lookup across 15+ specialties',
      'Appointment booking, rescheduling, and cancellation',
      'Token generation and synchronization with Suvarna ERP',
    ],
    allowedData: ['Doctor duty rosters', 'Clinic room allocations', 'Appointment slots', 'Patient booking history'],
    tools: ['slot_finder', 'suvarna_appointment_sync', 'token_generator'],
    permissions: ['read_schedules', 'create_appointment', 'cancel_appointment'],
    inputSchema: '{ department?: string, doctor_id?: string, preferred_date?: string, patient_id?: string }',
    outputSchema: '{ available_slots: array, booking_status: string, token: string }',
    escalationRules: 'If zero slots available for emergency/urgent case, route request to Doctor On-Call.',
    failureBehavior: 'Lock slot creation; offer manual receptionist fallback queue.',
  },
  queue_agent: {
    id: 'queue_agent',
    name: 'Queue & Waiting Agent',
    domain: 'Real-time Queues & Token Flow',
    responsibilities: [
      'Monitor waiting patient counts per department',
      'Calculate actual vs estimated waiting times',
      'Identify queue anomalies and sudden waiting surges',
    ],
    allowedData: ['Token queues', 'Check-in timestamps', 'Consultation duration averages'],
    tools: ['queue_calculator', 'wait_time_estimator', 'surge_detector'],
    permissions: ['read_queue_state', 'reprioritize_token', 'emit_queue_warning'],
    inputSchema: '{ department?: string, service?: string }',
    outputSchema: '{ waiting_count: number, avg_wait_minutes: number, delayed_tokens: array }',
    escalationRules: 'Alert Operations Agent if wait time exceeds double the SLA target.',
    failureBehavior: 'Report queue counts using last cached event sequence.',
  },
  doctor_agent: {
    id: 'doctor_agent',
    name: 'Doctor Agent',
    domain: 'Clinical Schedules & Reviews',
    responsibilities: [
      'Track doctor duty schedules, consultations, and rounds',
      'Surface pending diagnostic reviews (imaging & lab results)',
      'Coordinate clinical discharge clearances',
    ],
    allowedData: ['Doctor schedules', 'Assigned patient lists', 'Diagnostic reports awaiting sign-off'],
    tools: ['doctor_schedule_tool', 'pending_review_tool', 'clinical_clearance_tool'],
    permissions: ['read_doctor_schedule', 'read_clinical_notes', 'verify_clearance'],
    inputSchema: '{ doctor_id?: string, patient_id?: string }',
    outputSchema: '{ consultation_status: string, pending_reviews: array, clinical_clearance: boolean }',
    escalationRules: 'Notify HOD if critical diagnostic reports remain unreviewed > 60 minutes.',
    failureBehavior: 'Mark clinical review as UNVERIFIED; do not guess clinical status.',
  },
  nursing_agent: {
    id: 'nursing_agent',
    name: 'Nursing Agent',
    domain: 'Ward Care & Patient Movement',
    responsibilities: [
      'Coordinate nurse-to-patient allocations on ward floors',
      'Facilitate intra-hospital patient transport & vitals collection',
      'Assist in bed turnover and bedside discharge prep',
    ],
    allowedData: ['Ward duty rosters', 'Patient bed allocations', 'Bedside nursing tasks'],
    tools: ['nursing_roster_tool', 'bedside_task_tool', 'vitals_checker'],
    permissions: ['read_nursing_tasks', 'assign_nurse', 'log_movement'],
    inputSchema: '{ ward?: string, patient_id?: string }',
    outputSchema: '{ assigned_nurse: string, nursing_tasks_pending: array, patient_ready_for_move: boolean }',
    escalationRules: 'Escalate to Nursing Supervisor if nurse-to-patient ratio exceeds 1:6 in critical care.',
    failureBehavior: 'Log warning to Operations Agent and retain existing shift assignments.',
  },
  laboratory_agent: {
    id: 'laboratory_agent',
    name: 'Laboratory Agent',
    domain: 'Pathology & Diagnostics',
    responsibilities: [
      'Track lab test orders from phlebotomy to result delivery',
      'Monitor turnaround times for critical pathology panels',
      'Flag delayed test results blocking doctor decisions',
    ],
    allowedData: ['Lab test orders', 'Specimen barcode records', 'Pathology LIS status'],
    tools: ['lab_order_tracker', 'tat_monitor', 'critical_result_broadcaster'],
    permissions: ['read_lab_orders', 'read_test_results', 'flag_lab_delay'],
    inputSchema: '{ patient_id?: string, order_id?: string }',
    outputSchema: '{ orders: array, completed_count: number, delayed_count: number }',
    escalationRules: 'Notify ordering physician immediately if panic lab values are encountered.',
    failureBehavior: 'Mark lab results as PENDING_VERIFICATION; never simulate values.',
  },
  radiology_agent: {
    id: 'radiology_agent',
    name: 'Radiology Agent',
    domain: 'Imaging Modalities (MRI, CT, X-Ray)',
    responsibilities: [
      'Monitor MRI/CT/X-ray queues and scanner utilization',
      'Track imaging completion and radiologist report turnaround',
      'Detect equipment constraints and maintenance delays',
    ],
    allowedData: ['Scanner schedules', 'PACS imaging orders', 'Machine maintenance logs'],
    tools: ['radiology_schedule_tool', 'equipment_state_tool', 'imaging_order_tool'],
    permissions: ['read_imaging_orders', 'read_equipment_status', 'create_scheduling_request'],
    inputSchema: '{ patient_id?: string, modality?: string }',
    outputSchema: '{ scanner_status: object, queue_length: number, report_status: string }',
    escalationRules: 'Trigger immediate alert to Resource Agent if scanner downtime exceeds 30 minutes.',
    failureBehavior: 'Isolate affected scanner queue and reroute non-emergency studies.',
  },
  pharmacy_agent: {
    id: 'pharmacy_agent',
    name: 'Pharmacy Agent',
    domain: 'Medication Dispensing & Formulary',
    responsibilities: [
      'Verify prescription dispensing status for inpatient & discharge',
      'Check formulary stock and medicine availability',
      'Coordinate discharge medication readiness',
    ],
    allowedData: ['Pharmacy orders', 'Formulary stock levels', 'Dispensing bay queues'],
    tools: ['prescription_lookup', 'formulary_inventory_tool', 'dispense_verifier'],
    permissions: ['read_prescriptions', 'read_inventory', 'mark_medication_dispensed'],
    inputSchema: '{ patient_id: string }',
    outputSchema: '{ prescription_status: string, medications_ready: boolean, pending_items: array }',
    escalationRules: 'Cannot modify prescriptions under any condition; notify doctor on stockouts.',
    failureBehavior: 'Halt discharge medication release and flag pharmacist verification required.',
  },
  billing_agent: {
    id: 'billing_agent',
    name: 'Billing Agent',
    domain: 'Hospital Accounts & Patient Billing',
    responsibilities: [
      'Calculate inpatient billing ledgers and service itemizations',
      'Verify copays, deductibles, and outstanding patient balances',
      'Issue financial clearance certificate for patient discharge',
    ],
    allowedData: ['Billing ledgers', 'Itemized hospital tariffs', 'Payment transaction records'],
    tools: ['ledger_calculator', 'payment_gateway_verifier', 'discharge_clearance_tool'],
    permissions: ['read_billing_records', 'verify_payment', 'grant_discharge_clearance'],
    inputSchema: '{ patient_id: string }',
    outputSchema: '{ total_amount: number, balance_due: number, clearance_granted: boolean }',
    escalationRules: 'Discharge clearance blocked until outstanding balance reaches zero or approval granted.',
    failureBehavior: 'Block discharge clearance automatically until ledger can be validated.',
  },
  insurance_agent: {
    id: 'insurance_agent',
    name: 'Insurance & TPA Agent',
    domain: 'Health Insurance & Pre-Auth/Discharge Approval',
    responsibilities: [
      'Track Third-Party Administrator (TPA) authorization requests',
      'Monitor document submissions and pending insurance queries',
      'Expedite final discharge authorization from insurance providers',
    ],
    allowedData: ['Pre-auth requests', 'TPA portal status', 'Query submission records'],
    tools: ['tpa_portal_connector', 'query_tracker', 'escalation_dispatcher'],
    permissions: ['read_auth_status', 'submit_tpa_query_reply', 'trigger_tpa_escalation'],
    inputSchema: '{ patient_id: string }',
    outputSchema: '{ auth_status: string, approved_amount: number, queries_pending: string }',
    escalationRules: 'If TPA query is unanswered for > 2 hours on discharge day, raise HIGH severity alert.',
    failureBehavior: 'Report TPA status as UNCONFIRMED; request manual TPA desk intervention.',
  },
  bed_agent: {
    id: 'bed_agent',
    name: 'Bed Management Agent',
    domain: 'Inpatient Beds & Room Turnover',
    responsibilities: [
      'Track 300 hospital beds across general wards, step-down, and ICUs',
      'Monitor bed turnaround times (Occupied -> Vacated -> Cleaning -> Ready)',
      'Coordinate reserved bed allocations for emergency admissions',
    ],
    allowedData: ['Bed census', 'Housekeeping cleaning schedules', 'Ward ward-boy assignments'],
    tools: ['bed_census_tool', 'cleaning_status_tool', 'bed_reservation_tool'],
    permissions: ['read_bed_status', 'reserve_bed', 'release_bed', 'mark_cleaned'],
    inputSchema: '{ department?: string, bed_type?: string, status?: string }',
    outputSchema: '{ available_beds: array, occupied_count: number, cleaning_count: number }',
    escalationRules: 'If ICU availability falls below 2 beds, trigger EMERGENCY CRITICAL CAPACITY alert.',
    failureBehavior: 'Lock automatic bed assignments; require Head Nurse manual confirmation.',
  },
  admission_agent: {
    id: 'admission_agent',
    name: 'Admission Agent',
    domain: 'Inpatient Registration & Onboarding',
    responsibilities: [
      'Coordinate inpatient admission workflows from OPD/Emergency',
      'Verify clinical doctor admission orders and patient consents',
      'Bridge bed allocation with nursing reception',
    ],
    allowedData: ['Admission orders', 'Patient demographics', 'Insurance pre-auth status'],
    tools: ['admission_order_verifier', 'suvarna_admit_sync', 'welcome_packet_generator'],
    permissions: ['create_admission_record', 'verify_admission_order'],
    inputSchema: '{ patient_id: string, department: string, doctor_id: string }',
    outputSchema: '{ admission_status: string, assigned_bed: string, readiness: boolean }',
    escalationRules: 'If emergency admission lacks bed assignment within 15 minutes, trigger Code Orange.',
    failureBehavior: 'Hold in Emergency holding bay until supervisor confirms ward bed.',
  },
  discharge_agent: {
    id: 'discharge_agent',
    name: 'Discharge Agent',
    domain: 'Discharge Orchestration & Blocker Resolution',
    responsibilities: [
      'Monitor multi-department discharge checklist for inpatients',
      'Orchestrate parallel checks: Clinical, Pharmacy, Billing, TPA, Bed Release',
      'Identify root-cause blockers delaying bed release',
    ],
    allowedData: ['Discharge checklists', 'Clinical discharge orders', 'Clearance tokens'],
    tools: ['checklist_orchestrator', 'blocker_analyzer', 'discharge_summary_tool'],
    permissions: ['read_discharge_checklist', 'trigger_clearance_verification', 'complete_discharge'],
    inputSchema: '{ patient_id: string }',
    outputSchema: '{ is_discharge_ready: boolean, blockers: array, primary_blocker: string }',
    escalationRules: 'When discharge is delayed > 60 mins past planned time, summon cross-functional review.',
    failureBehavior: 'Safe fail-closed: do not allow patient physical exit without confirmed clearance.',
  },
  bottleneck_agent: {
    id: 'bottleneck_agent',
    name: 'Bottleneck Agent',
    domain: 'Hospital Delay & Constraint Detection',
    responsibilities: [
      'Detect real-time process bottlenecks across all 15+ departments',
      'Analyze dependency graphs and calculate delay cascade propagation',
      'Classify constraint severity and highlight affected patient cohorts',
    ],
    allowedData: ['Department queue lengths', 'Equipment idle/busy times', 'Journey stage durations'],
    tools: ['dependency_graph_analyzer', 'cascade_calculator', 'severity_classifier'],
    permissions: ['read_all_metrics', 'publish_bottleneck_warning'],
    inputSchema: '{ department?: string, patient_id?: string }',
    outputSchema: '{ bottlenecks: array, critical_constraints: array, cascade_impact: string }',
    escalationRules: 'Automatically notify Operations Agent on CRITICAL severity classification.',
    failureBehavior: 'Preserve existing bottleneck cache and flag metric sampling latency.',
  },
  resource_agent: {
    id: 'resource_agent',
    name: 'Resource Agent',
    domain: 'Hospital Assets & Equipment',
    responsibilities: [
      'Track equipment operational health (MRIs, CT scanners, OR suites, ventilators)',
      'Monitor transport wheelchairs, stretchers, and staff readiness',
      'Manage preventative maintenance and equipment downtime impact',
    ],
    allowedData: ['Asset registry', 'Maintenance logs', 'Resource reservation schedules'],
    tools: ['equipment_monitor', 'utilization_calculator', 'maintenance_scheduler'],
    permissions: ['read_equipment_health', 'flag_equipment_maintenance', 'reallocate_resource'],
    inputSchema: '{ resource_type?: string, department?: string }',
    outputSchema: '{ resources: array, utilization_rate: number, maintenance_alerts: array }',
    escalationRules: 'Alert Biomedical Engineering instantly if critical life-support or diagnostic unit faults.',
    failureBehavior: 'Mark offline resources as UNAVAILABLE; prohibit scheduling onto that asset.',
  },
  operations_agent: {
    id: 'operations_agent',
    name: 'Operations Agent',
    domain: 'Enterprise Hospital Operations',
    responsibilities: [
      'Synthesize hospital-wide operational health and patient flow velocity',
      'Correlate cross-department bottlenecks and formulate action plans',
      'Present actionable recommendations for Administrator approval',
    ],
    allowedData: ['Cross-departmental KPIs', 'Bed census', 'Daily admission/discharge counts'],
    tools: ['kpi_aggregator', 'recommendation_engine', 'action_plan_builder'],
    permissions: ['generate_operational_recommendations', 'request_admin_approval'],
    inputSchema: '{ scope: string, include_proposals?: boolean }',
    outputSchema: '{ executive_summary: string, bottlenecks_identified: array, proposals: array }',
    escalationRules: 'Require explicit Hospital Administrator approval before executing reassignments.',
    failureBehavior: 'Output conservative contingency protocols and alert human Ops Director.',
  },
  finance_agent: {
    id: 'finance_agent',
    name: 'Finance Agent',
    domain: 'Operational Finance & Revenue Cycle',
    responsibilities: [
      'Provide authorized operational financial summaries per department',
      'Analyze outstanding discharge balances and uncollected revenue',
      'Monitor TPA settlement cycle times and revenue leakage points',
    ],
    allowedData: ['Department revenue aggregates', 'Outstanding TPA balances', 'Billing clearance throughput'],
    tools: ['financial_summary_tool', 'aging_receivables_calculator', 'tpa_cycle_monitor'],
    permissions: ['read_authorized_financials', 'generate_revenue_summary'],
    inputSchema: '{ department?: string, time_window?: string }',
    outputSchema: '{ gross_revenue_today: number, pending_claims_value: number, collections_rate: number }',
    escalationRules: 'Flag to CFO if cumulative delayed discharge claims exceed ₹25 Lakhs in a single day.',
    failureBehavior: 'Mask detailed ledger values; output high-level operational indicators only.',
  },
};
